# Generated by Django 2.1.3 on 2018-11-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("city", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="building",
            name="datetime_build_started",
            field=models.DateTimeField(
                null=True, verbose_name="Czas rozpoczęcia budowy"
            ),
        )
    ]
