# Generated by Django 2.1.3 on 2018-11-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("city", "0002_building_datetime_build_started")]

    operations = [
        migrations.RemoveField(model_name="patrol2", name="number_of_built_buildings"),
        migrations.AlterField(
            model_name="building",
            name="cost",
            field=models.FloatField(
                default=100, verbose_name="Koszt budowy budynku w guldenach"
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="generate_people",
            field=models.FloatField(default=1, verbose_name="Przychód guldenów"),
        ),
        migrations.AlterField(
            model_name="building",
            name="generate_points",
            field=models.FloatField(default=1, verbose_name="Wzrost ludności"),
        ),
        migrations.AlterField(
            model_name="patrol2",
            name="money",
            field=models.FloatField(default=0, verbose_name="Guldeny"),
        ),
        migrations.AlterField(
            model_name="patrol2",
            name="people",
            field=models.FloatField(default=0, verbose_name="Ludność"),
        ),
    ]
