# Generated by Django 2.1.3 on 2018-11-09 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("city", "0002_rule")]

    operations = [
        migrations.CreateModel(
            name="UsedBonusCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "datetime_used",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Czas wykorzystania kodu"
                    ),
                ),
                (
                    "bonus_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="city.BonusCode",
                        verbose_name="Wykorzystany Kod",
                    ),
                ),
                (
                    "patrol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="city.Patrol2",
                        verbose_name="Patrol",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="share",
            name="date_bought",
            field=models.DateField(auto_now_add=True, verbose_name="Data zakupu"),
        ),
    ]
