# Generated by Django 2.1.3 on 2018-11-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("city", "0003_auto_20181109_1043")]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="generate_people",
            field=models.FloatField(default=1, verbose_name="Wzrost ludności"),
        ),
        migrations.AlterField(
            model_name="building",
            name="generate_points",
            field=models.FloatField(default=1, verbose_name="Przychód guldenów"),
        ),
    ]
