# Generated by Django 2.1.3 on 2018-11-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("city", "0003_auto_20181109_0113")]

    operations = [
        migrations.RemoveField(model_name="bonuscode", name="bonus"),
        migrations.RemoveField(model_name="patrol2", name="built_buildings"),
        migrations.RemoveField(model_name="patrol2", name="usedcodes"),
        migrations.AddField(
            model_name="bonuscode",
            name="value",
            field=models.IntegerField(
                default=100, verbose_name="Guldeny przyznawane za kod"
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="date_bought",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data zakupu"),
        ),
    ]
