# Generated by Django 2.1.3 on 2018-11-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_auto_20181109_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='datetime_build_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas rozpoczęcia budowy'),
        ),
    ]
