# Generated by Django 2.1.3 on 2018-11-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181105_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='xddd',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
