# Generated by Django 2.1.3 on 2018-11-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_xddd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='xddd',
        ),
    ]
