# Generated by Django 2.1.3 on 2018-11-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_xddd'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usedpoints',
            field=models.TextField(default='xdddddd'),
        ),
    ]
