# Generated by Django 2.1.3 on 2018-11-06 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181106_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dworcowa10',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='dworcowa13',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='dworcowa3',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
