# Generated by Django 2.1.3 on 2018-11-07 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20181106_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('built', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='building_pic')),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='Patrol',
        ),
        migrations.RenameField(
            model_name='patrol',
            old_name='usedpoints',
            new_name='usedcodes',
        ),
    ]
