# Generated by Django 2.1.3 on 2018-11-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181108_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.URLField(),
        ),
    ]
