# Generated by Django 2.1.3 on 2018-11-07 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181108_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='patrol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
