# Generated by Django 2.1.3 on 2018-11-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20181108_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patrol',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
