# Generated by Django 2.1.3 on 2018-11-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181108_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrol',
            name='built_buildings',
            field=models.TextField(default='xdddddd'),
        ),
        migrations.AddField(
            model_name='patrol',
            name='number_of_built_buildings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
