# Generated by Django 2.1.3 on 2018-11-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20181108_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Big_Building',
            fields=[
                ('name', models.TextField()),
                ('how_much_built', models.PositiveIntegerField(default=0)),
                ('size', models.PositiveIntegerField(default=4)),
                ('image', models.URLField()),
                ('patrol', models.TextField(default=' ')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
