# Generated by Django 2.1.3 on 2018-11-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_big_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrol',
            name='dworcowa10',
        ),
        migrations.RemoveField(
            model_name='patrol',
            name='dworcowa13',
        ),
        migrations.RemoveField(
            model_name='patrol',
            name='dworcowa3',
        ),
        migrations.AlterField(
            model_name='big_building',
            name='image',
            field=models.URLField(blank=True, default='https://ebilet-media.azureedge.net/media/18709/teatr-dom-git450.jpg', null=True),
        ),
        migrations.AlterField(
            model_name='big_building',
            name='patrol',
            field=models.TextField(blank=True, default='!', null=True),
        ),
    ]
