# Generated by Django 2.1.3 on 2018-11-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dworcowa3', models.BooleanField(default=0)),
                ('dworcowa10', models.BooleanField(default=0)),
                ('dworcowa13', models.BooleanField(default=0)),
            ],
        ),
    ]
