# Generated by Django 2.1.3 on 2018-11-06 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181106_0153'),
        ('blog', '0002_buildings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buildings',
        ),
    ]
